// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cvproject/cv.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CV struct {
	Index      uint64     `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name       string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Education  string     `protobuf:"bytes,3,opt,name=education,proto3" json:"education,omitempty"`
	Summary    string     `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Skills     string     `protobuf:"bytes,5,opt,name=skills,proto3" json:"skills,omitempty"`
	Experience string     `protobuf:"bytes,6,opt,name=experience,proto3" json:"experience,omitempty"`
	Creator    string     `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
	Companies  []*Company `protobuf:"bytes,8,rep,name=Companies,proto3" json:"Companies,omitempty"`
}

func (m *CV) Reset()         { *m = CV{} }
func (m *CV) String() string { return proto.CompactTextString(m) }
func (*CV) ProtoMessage()    {}
func (*CV) Descriptor() ([]byte, []int) {
	return fileDescriptor_3612606c94a40498, []int{0}
}
func (m *CV) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CV.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CV.Merge(m, src)
}
func (m *CV) XXX_Size() int {
	return m.Size()
}
func (m *CV) XXX_DiscardUnknown() {
	xxx_messageInfo_CV.DiscardUnknown(m)
}

var xxx_messageInfo_CV proto.InternalMessageInfo

func (m *CV) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *CV) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CV) GetEducation() string {
	if m != nil {
		return m.Education
	}
	return ""
}

func (m *CV) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *CV) GetSkills() string {
	if m != nil {
		return m.Skills
	}
	return ""
}

func (m *CV) GetExperience() string {
	if m != nil {
		return m.Experience
	}
	return ""
}

func (m *CV) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CV) GetCompanies() []*Company {
	if m != nil {
		return m.Companies
	}
	return nil
}

type Company struct {
	Uuid           string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TimestampStart string `protobuf:"bytes,3,opt,name=timestamp_start,json=timestampStart,proto3" json:"timestamp_start,omitempty"`
	TimestampEnd   string `protobuf:"bytes,4,opt,name=timestamp_end,json=timestampEnd,proto3" json:"timestamp_end,omitempty"`
	Comments       string `protobuf:"bytes,5,opt,name=comments,proto3" json:"comments,omitempty"`
}

func (m *Company) Reset()         { *m = Company{} }
func (m *Company) String() string { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()    {}
func (*Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_3612606c94a40498, []int{1}
}
func (m *Company) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Company.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Company.Merge(m, src)
}
func (m *Company) XXX_Size() int {
	return m.Size()
}
func (m *Company) XXX_DiscardUnknown() {
	xxx_messageInfo_Company.DiscardUnknown(m)
}

var xxx_messageInfo_Company proto.InternalMessageInfo

func (m *Company) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Company) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Company) GetTimestampStart() string {
	if m != nil {
		return m.TimestampStart
	}
	return ""
}

func (m *Company) GetTimestampEnd() string {
	if m != nil {
		return m.TimestampEnd
	}
	return ""
}

func (m *Company) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func init() {
	proto.RegisterType((*CV)(nil), "alexs778.cvproject.cvproject.CV")
	proto.RegisterType((*Company)(nil), "alexs778.cvproject.cvproject.Company")
}

func init() { proto.RegisterFile("cvproject/cv.proto", fileDescriptor_3612606c94a40498) }

var fileDescriptor_3612606c94a40498 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x8a, 0xdb, 0x30,
	0x10, 0xc6, 0xa3, 0xfc, 0xb7, 0xfa, 0x0f, 0x44, 0x29, 0xa2, 0x04, 0x13, 0x52, 0x4a, 0x73, 0xb2,
	0xa1, 0x3d, 0x38, 0xd7, 0xd6, 0xf4, 0xd0, 0x5b, 0x71, 0x20, 0x87, 0x5e, 0x8a, 0x22, 0x0f, 0xbb,
	0xda, 0xb5, 0x24, 0x63, 0xc9, 0xc1, 0x79, 0x8b, 0xbd, 0xef, 0x0b, 0xed, 0x31, 0xc7, 0x3d, 0x2e,
	0xc9, 0x73, 0x2c, 0x2c, 0x51, 0x1c, 0x7b, 0x0f, 0xcb, 0xde, 0xe6, 0xfb, 0x7d, 0xa3, 0x81, 0xf9,
	0x34, 0x98, 0xf0, 0x4d, 0x5e, 0xe8, 0x2b, 0xe0, 0x36, 0xe4, 0x9b, 0x20, 0x2f, 0xb4, 0xd5, 0x64,
	0xc2, 0x32, 0xa8, 0x4c, 0x14, 0x2d, 0x82, 0xc6, 0x6c, 0xab, 0xd9, 0x23, 0xc2, 0xdd, 0x78, 0x45,
	0x3e, 0xe2, 0x81, 0x50, 0x29, 0x54, 0x14, 0x4d, 0xd1, 0xbc, 0x9f, 0x9c, 0x04, 0x21, 0xb8, 0xaf,
	0x98, 0x04, 0xda, 0x9d, 0xa2, 0xb9, 0x97, 0xb8, 0x9a, 0x4c, 0xb0, 0x07, 0x69, 0xc9, 0x99, 0x15,
	0x5a, 0xd1, 0x9e, 0x33, 0x5a, 0x40, 0x28, 0x1e, 0x99, 0x52, 0x4a, 0x56, 0x6c, 0x69, 0xdf, 0x79,
	0x67, 0x49, 0x3e, 0xe1, 0xa1, 0xb9, 0x16, 0x59, 0x66, 0xe8, 0xc0, 0x19, 0xb5, 0x22, 0x3e, 0xc6,
	0x50, 0xe5, 0x50, 0x08, 0x50, 0x1c, 0xe8, 0xd0, 0x79, 0xcf, 0xc8, 0x71, 0x22, 0x2f, 0x80, 0x59,
	0x5d, 0xd0, 0xd1, 0x69, 0x62, 0x2d, 0x49, 0x8c, 0xbd, 0x58, 0xcb, 0x9c, 0x29, 0x01, 0x86, 0x8e,
	0xa7, 0xbd, 0xf9, 0x9b, 0xef, 0x5f, 0x83, 0xd7, 0x96, 0x0d, 0x4e, 0xed, 0xdb, 0xa4, 0x7d, 0x37,
	0xbb, 0x45, 0x78, 0x54, 0xe3, 0xe3, 0xba, 0x65, 0x29, 0x52, 0x97, 0x81, 0x97, 0xb8, 0xfa, 0xc5,
	0x08, 0xbe, 0xe1, 0x0f, 0x56, 0x48, 0x30, 0x96, 0xc9, 0xfc, 0xbf, 0xb1, 0xac, 0xb0, 0x75, 0x10,
	0xef, 0x1b, 0xbc, 0x3c, 0x52, 0xf2, 0x05, 0xbf, 0x6b, 0x1b, 0x41, 0xa5, 0x75, 0x26, 0x6f, 0x1b,
	0xf8, 0x5b, 0xa5, 0xe4, 0x33, 0x1e, 0x73, 0x2d, 0x25, 0x28, 0x7b, 0x8e, 0xa6, 0xd1, 0xbf, 0xfe,
	0xdc, 0xed, 0x7d, 0xb4, 0xdb, 0xfb, 0xe8, 0x61, 0xef, 0xa3, 0x9b, 0x83, 0xdf, 0xd9, 0x1d, 0xfc,
	0xce, 0xfd, 0xc1, 0xef, 0xfc, 0x0b, 0x2f, 0x84, 0xbd, 0x2c, 0xd7, 0x01, 0xd7, 0x32, 0xfc, 0x99,
	0x41, 0xb5, 0x8c, 0xa2, 0x45, 0x18, 0xaf, 0xfe, 0xd6, 0xbf, 0x5f, 0x85, 0xed, 0x25, 0xd8, 0x6d,
	0x0e, 0x66, 0x3d, 0x74, 0xd7, 0xf0, 0xe3, 0x29, 0x00, 0x00, 0xff, 0xff, 0x84, 0xaf, 0xc0, 0xbe,
	0x23, 0x02, 0x00, 0x00,
}

func (m *CV) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CV) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CV) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Companies) > 0 {
		for iNdEx := len(m.Companies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Companies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCv(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Experience) > 0 {
		i -= len(m.Experience)
		copy(dAtA[i:], m.Experience)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Experience)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Skills) > 0 {
		i -= len(m.Skills)
		copy(dAtA[i:], m.Skills)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Skills)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Summary) > 0 {
		i -= len(m.Summary)
		copy(dAtA[i:], m.Summary)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Summary)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Education) > 0 {
		i -= len(m.Education)
		copy(dAtA[i:], m.Education)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Education)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintCv(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Company) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Company) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Company) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Comments) > 0 {
		i -= len(m.Comments)
		copy(dAtA[i:], m.Comments)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Comments)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TimestampEnd) > 0 {
		i -= len(m.TimestampEnd)
		copy(dAtA[i:], m.TimestampEnd)
		i = encodeVarintCv(dAtA, i, uint64(len(m.TimestampEnd)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TimestampStart) > 0 {
		i -= len(m.TimestampStart)
		copy(dAtA[i:], m.TimestampStart)
		i = encodeVarintCv(dAtA, i, uint64(len(m.TimestampStart)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCv(dAtA []byte, offset int, v uint64) int {
	offset -= sovCv(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CV) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovCv(uint64(m.Index))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Education)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Summary)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Skills)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Experience)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	if len(m.Companies) > 0 {
		for _, e := range m.Companies {
			l = e.Size()
			n += 1 + l + sovCv(uint64(l))
		}
	}
	return n
}

func (m *Company) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.TimestampStart)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.TimestampEnd)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Comments)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	return n
}

func sovCv(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCv(x uint64) (n int) {
	return sovCv(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CV) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CV: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CV: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Education", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Education = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Summary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Summary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skills", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Skills = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Experience", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Experience = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Companies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Companies = append(m.Companies, &Company{})
			if err := m.Companies[len(m.Companies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Company) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Company: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Company: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampStart", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimestampStart = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampEnd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimestampEnd = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comments", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comments = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCv(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCv
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCv
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCv
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCv
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCv
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCv
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCv        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCv          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCv = fmt.Errorf("proto: unexpected end of group")
)
