// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cvproject/cv.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CV struct {
	Name          string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Education     string   `protobuf:"bytes,2,opt,name=education,proto3" json:"education,omitempty"`
	Summary       string   `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Skills        string   `protobuf:"bytes,4,opt,name=skills,proto3" json:"skills,omitempty"`
	Experience    string   `protobuf:"bytes,5,opt,name=experience,proto3" json:"experience,omitempty"`
	Creator       string   `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	CompaniesUUID []string `protobuf:"bytes,7,rep,name=CompaniesUUID,proto3" json:"CompaniesUUID,omitempty"`
}

func (m *CV) Reset()         { *m = CV{} }
func (m *CV) String() string { return proto.CompactTextString(m) }
func (*CV) ProtoMessage()    {}
func (*CV) Descriptor() ([]byte, []int) {
	return fileDescriptor_3612606c94a40498, []int{0}
}
func (m *CV) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CV.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CV.Merge(m, src)
}
func (m *CV) XXX_Size() int {
	return m.Size()
}
func (m *CV) XXX_DiscardUnknown() {
	xxx_messageInfo_CV.DiscardUnknown(m)
}

var xxx_messageInfo_CV proto.InternalMessageInfo

func (m *CV) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CV) GetEducation() string {
	if m != nil {
		return m.Education
	}
	return ""
}

func (m *CV) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *CV) GetSkills() string {
	if m != nil {
		return m.Skills
	}
	return ""
}

func (m *CV) GetExperience() string {
	if m != nil {
		return m.Experience
	}
	return ""
}

func (m *CV) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CV) GetCompaniesUUID() []string {
	if m != nil {
		return m.CompaniesUUID
	}
	return nil
}

type CvForResponse struct {
	Name       string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Education  string             `protobuf:"bytes,2,opt,name=education,proto3" json:"education,omitempty"`
	Summary    string             `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Skills     string             `protobuf:"bytes,4,opt,name=skills,proto3" json:"skills,omitempty"`
	Experience string             `protobuf:"bytes,5,opt,name=experience,proto3" json:"experience,omitempty"`
	Creator    string             `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Companies  []*CompanyWorkedIn `protobuf:"bytes,7,rep,name=Companies,proto3" json:"Companies,omitempty"`
}

func (m *CvForResponse) Reset()         { *m = CvForResponse{} }
func (m *CvForResponse) String() string { return proto.CompactTextString(m) }
func (*CvForResponse) ProtoMessage()    {}
func (*CvForResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3612606c94a40498, []int{1}
}
func (m *CvForResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CvForResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CvForResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CvForResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CvForResponse.Merge(m, src)
}
func (m *CvForResponse) XXX_Size() int {
	return m.Size()
}
func (m *CvForResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CvForResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CvForResponse proto.InternalMessageInfo

func (m *CvForResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CvForResponse) GetEducation() string {
	if m != nil {
		return m.Education
	}
	return ""
}

func (m *CvForResponse) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *CvForResponse) GetSkills() string {
	if m != nil {
		return m.Skills
	}
	return ""
}

func (m *CvForResponse) GetExperience() string {
	if m != nil {
		return m.Experience
	}
	return ""
}

func (m *CvForResponse) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CvForResponse) GetCompanies() []*CompanyWorkedIn {
	if m != nil {
		return m.Companies
	}
	return nil
}

func init() {
	proto.RegisterType((*CV)(nil), "alexs778.cvproject.cvproject.CV")
	proto.RegisterType((*CvForResponse)(nil), "alexs778.cvproject.cvproject.CvForResponse")
}

func init() { proto.RegisterFile("cvproject/cv.proto", fileDescriptor_3612606c94a40498) }

var fileDescriptor_3612606c94a40498 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x52, 0x31, 0x4f, 0xc2, 0x40,
	0x18, 0xe5, 0x00, 0x21, 0x3d, 0xc3, 0x72, 0x83, 0xb9, 0x18, 0x72, 0x41, 0xe2, 0xc0, 0x62, 0x9b,
	0xe8, 0x50, 0x56, 0xad, 0x31, 0x21, 0x2e, 0xa6, 0x06, 0x4c, 0x5c, 0x48, 0x39, 0xbe, 0x68, 0xa5,
	0xbd, 0x6b, 0xee, 0x0a, 0xb6, 0xff, 0xc2, 0x9f, 0xc5, 0xc8, 0xe8, 0x68, 0xe0, 0x5f, 0x38, 0x19,
	0x8f, 0x4a, 0x71, 0x71, 0x76, 0xfb, 0xde, 0x7b, 0xf7, 0xbd, 0xdc, 0xcb, 0xf7, 0x30, 0xe1, 0x8b,
	0x44, 0xc9, 0x17, 0xe0, 0xa9, 0xc3, 0x17, 0x76, 0xa2, 0x64, 0x2a, 0x49, 0x3b, 0x88, 0x20, 0xd3,
	0xae, 0xdb, 0xb7, 0x77, 0x62, 0x39, 0x1d, 0x9f, 0xec, 0x6d, 0xc8, 0x38, 0x09, 0x44, 0x3e, 0x7e,
	0x95, 0x6a, 0x06, 0xd3, 0x71, 0x28, 0xb6, 0x06, 0xdd, 0x25, 0xc2, 0x55, 0x6f, 0x44, 0x08, 0xae,
	0x8b, 0x20, 0x06, 0x8a, 0x3a, 0xa8, 0x67, 0xf9, 0x66, 0x26, 0x6d, 0x6c, 0xc1, 0x74, 0xce, 0x83,
	0x34, 0x94, 0x82, 0x56, 0x8d, 0x50, 0x12, 0x84, 0xe2, 0xa6, 0x9e, 0xc7, 0x71, 0xa0, 0x72, 0x5a,
	0x33, 0xda, 0x0f, 0x24, 0x47, 0xb8, 0xa1, 0x67, 0x61, 0x14, 0x69, 0x5a, 0x37, 0x42, 0x81, 0x08,
	0xc3, 0x18, 0xb2, 0x04, 0x54, 0x08, 0x82, 0x03, 0x3d, 0x30, 0xda, 0x1e, 0xf3, 0xed, 0xc8, 0x15,
	0x04, 0xa9, 0x54, 0xb4, 0xb1, 0x75, 0x2c, 0x20, 0x39, 0xc5, 0x2d, 0xcf, 0xfc, 0x3f, 0x04, 0x3d,
	0x1c, 0x0e, 0xae, 0x69, 0xb3, 0x53, 0xeb, 0x59, 0xfe, 0x6f, 0xb2, 0xfb, 0x89, 0x70, 0xcb, 0x5b,
	0xdc, 0x48, 0xe5, 0x83, 0x4e, 0xa4, 0xd0, 0xf0, 0xcf, 0x53, 0xdd, 0x62, 0x6b, 0x17, 0xc0, 0x24,
	0x3a, 0x3c, 0x3f, 0xb3, 0xff, 0xba, 0xa7, 0xbd, 0x7d, 0x9e, 0x3f, 0x98, 0x1b, 0x0e, 0x84, 0x5f,
	0xee, 0x5f, 0x0d, 0x96, 0x6b, 0x86, 0x56, 0x6b, 0x86, 0x3e, 0xd6, 0x0c, 0xbd, 0x6d, 0x58, 0x65,
	0xb5, 0x61, 0x95, 0xf7, 0x0d, 0xab, 0x3c, 0x3a, 0x4f, 0x61, 0xfa, 0x3c, 0x9f, 0xd8, 0x5c, 0xc6,
	0xce, 0x65, 0x04, 0xd9, 0xbd, 0xeb, 0xf6, 0x1d, 0x6f, 0x74, 0x57, 0x14, 0x23, 0x73, 0xca, 0x92,
	0xa4, 0x79, 0x02, 0x7a, 0xd2, 0x30, 0xcd, 0xb8, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x41,
	0x48, 0x7b, 0x70, 0x02, 0x00, 0x00,
}

func (m *CV) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CV) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CV) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CompaniesUUID) > 0 {
		for iNdEx := len(m.CompaniesUUID) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CompaniesUUID[iNdEx])
			copy(dAtA[i:], m.CompaniesUUID[iNdEx])
			i = encodeVarintCv(dAtA, i, uint64(len(m.CompaniesUUID[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Experience) > 0 {
		i -= len(m.Experience)
		copy(dAtA[i:], m.Experience)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Experience)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Skills) > 0 {
		i -= len(m.Skills)
		copy(dAtA[i:], m.Skills)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Skills)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Summary) > 0 {
		i -= len(m.Summary)
		copy(dAtA[i:], m.Summary)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Summary)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Education) > 0 {
		i -= len(m.Education)
		copy(dAtA[i:], m.Education)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Education)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CvForResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CvForResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CvForResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Companies) > 0 {
		for iNdEx := len(m.Companies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Companies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCv(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Experience) > 0 {
		i -= len(m.Experience)
		copy(dAtA[i:], m.Experience)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Experience)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Skills) > 0 {
		i -= len(m.Skills)
		copy(dAtA[i:], m.Skills)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Skills)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Summary) > 0 {
		i -= len(m.Summary)
		copy(dAtA[i:], m.Summary)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Summary)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Education) > 0 {
		i -= len(m.Education)
		copy(dAtA[i:], m.Education)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Education)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCv(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCv(dAtA []byte, offset int, v uint64) int {
	offset -= sovCv(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CV) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Education)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Summary)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Skills)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Experience)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	if len(m.CompaniesUUID) > 0 {
		for _, s := range m.CompaniesUUID {
			l = len(s)
			n += 1 + l + sovCv(uint64(l))
		}
	}
	return n
}

func (m *CvForResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Education)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Summary)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Skills)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Experience)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCv(uint64(l))
	}
	if len(m.Companies) > 0 {
		for _, e := range m.Companies {
			l = e.Size()
			n += 1 + l + sovCv(uint64(l))
		}
	}
	return n
}

func sovCv(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCv(x uint64) (n int) {
	return sovCv(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CV) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CV: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CV: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Education", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Education = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Summary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Summary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skills", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Skills = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Experience", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Experience = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompaniesUUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CompaniesUUID = append(m.CompaniesUUID, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CvForResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CvForResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CvForResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Education", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Education = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Summary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Summary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skills", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Skills = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Experience", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Experience = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Companies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Companies = append(m.Companies, &CompanyWorkedIn{})
			if err := m.Companies[len(m.Companies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCv(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCv
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCv
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCv
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCv
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCv
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCv
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCv        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCv          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCv = fmt.Errorf("proto: unexpected end of group")
)
