// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cvproject/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateCV struct {
	Creator       string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name          string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Education     string   `protobuf:"bytes,3,opt,name=education,proto3" json:"education,omitempty"`
	Summary       string   `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Skills        string   `protobuf:"bytes,5,opt,name=skills,proto3" json:"skills,omitempty"`
	Experience    string   `protobuf:"bytes,6,opt,name=experience,proto3" json:"experience,omitempty"`
	CompaniesUUID []string `protobuf:"bytes,7,rep,name=companiesUUID,proto3" json:"companiesUUID,omitempty"`
}

func (m *MsgCreateCV) Reset()         { *m = MsgCreateCV{} }
func (m *MsgCreateCV) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCV) ProtoMessage()    {}
func (*MsgCreateCV) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5056c0d43a94ec1, []int{0}
}
func (m *MsgCreateCV) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCV.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCV.Merge(m, src)
}
func (m *MsgCreateCV) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCV) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCV.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCV proto.InternalMessageInfo

func (m *MsgCreateCV) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateCV) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCreateCV) GetEducation() string {
	if m != nil {
		return m.Education
	}
	return ""
}

func (m *MsgCreateCV) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *MsgCreateCV) GetSkills() string {
	if m != nil {
		return m.Skills
	}
	return ""
}

func (m *MsgCreateCV) GetExperience() string {
	if m != nil {
		return m.Experience
	}
	return ""
}

func (m *MsgCreateCV) GetCompaniesUUID() []string {
	if m != nil {
		return m.CompaniesUUID
	}
	return nil
}

type MsgCreateCVResponse struct {
}

func (m *MsgCreateCVResponse) Reset()         { *m = MsgCreateCVResponse{} }
func (m *MsgCreateCVResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCVResponse) ProtoMessage()    {}
func (*MsgCreateCVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5056c0d43a94ec1, []int{1}
}
func (m *MsgCreateCVResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCVResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCVResponse.Merge(m, src)
}
func (m *MsgCreateCVResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCVResponse proto.InternalMessageInfo

type MsgUpdateCV struct {
	Creator       string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CosmosAdress  string   `protobuf:"bytes,2,opt,name=cosmosAdress,proto3" json:"cosmosAdress,omitempty"`
	Name          string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Education     string   `protobuf:"bytes,4,opt,name=education,proto3" json:"education,omitempty"`
	Summary       string   `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Skills        string   `protobuf:"bytes,6,opt,name=skills,proto3" json:"skills,omitempty"`
	Experience    string   `protobuf:"bytes,7,opt,name=experience,proto3" json:"experience,omitempty"`
	CompaniesUUID []string `protobuf:"bytes,8,rep,name=companiesUUID,proto3" json:"companiesUUID,omitempty"`
}

func (m *MsgUpdateCV) Reset()         { *m = MsgUpdateCV{} }
func (m *MsgUpdateCV) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCV) ProtoMessage()    {}
func (*MsgUpdateCV) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5056c0d43a94ec1, []int{2}
}
func (m *MsgUpdateCV) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCV.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCV.Merge(m, src)
}
func (m *MsgUpdateCV) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCV) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCV.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCV proto.InternalMessageInfo

func (m *MsgUpdateCV) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateCV) GetCosmosAdress() string {
	if m != nil {
		return m.CosmosAdress
	}
	return ""
}

func (m *MsgUpdateCV) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgUpdateCV) GetEducation() string {
	if m != nil {
		return m.Education
	}
	return ""
}

func (m *MsgUpdateCV) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *MsgUpdateCV) GetSkills() string {
	if m != nil {
		return m.Skills
	}
	return ""
}

func (m *MsgUpdateCV) GetExperience() string {
	if m != nil {
		return m.Experience
	}
	return ""
}

func (m *MsgUpdateCV) GetCompaniesUUID() []string {
	if m != nil {
		return m.CompaniesUUID
	}
	return nil
}

type MsgUpdateCVResponse struct {
}

func (m *MsgUpdateCVResponse) Reset()         { *m = MsgUpdateCVResponse{} }
func (m *MsgUpdateCVResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCVResponse) ProtoMessage()    {}
func (*MsgUpdateCVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5056c0d43a94ec1, []int{3}
}
func (m *MsgUpdateCVResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCVResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCVResponse.Merge(m, src)
}
func (m *MsgUpdateCVResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCVResponse proto.InternalMessageInfo

type MsgConfirmCV struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CosmosAdress string `protobuf:"bytes,3,opt,name=cosmosAdress,proto3" json:"cosmosAdress,omitempty"`
}

func (m *MsgConfirmCV) Reset()         { *m = MsgConfirmCV{} }
func (m *MsgConfirmCV) String() string { return proto.CompactTextString(m) }
func (*MsgConfirmCV) ProtoMessage()    {}
func (*MsgConfirmCV) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5056c0d43a94ec1, []int{4}
}
func (m *MsgConfirmCV) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfirmCV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfirmCV.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfirmCV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfirmCV.Merge(m, src)
}
func (m *MsgConfirmCV) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfirmCV) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfirmCV.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfirmCV proto.InternalMessageInfo

func (m *MsgConfirmCV) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgConfirmCV) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgConfirmCV) GetCosmosAdress() string {
	if m != nil {
		return m.CosmosAdress
	}
	return ""
}

type MsgConfirmCVResponse struct {
}

func (m *MsgConfirmCVResponse) Reset()         { *m = MsgConfirmCVResponse{} }
func (m *MsgConfirmCVResponse) String() string { return proto.CompactTextString(m) }
func (*MsgConfirmCVResponse) ProtoMessage()    {}
func (*MsgConfirmCVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5056c0d43a94ec1, []int{5}
}
func (m *MsgConfirmCVResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfirmCVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfirmCVResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfirmCVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfirmCVResponse.Merge(m, src)
}
func (m *MsgConfirmCVResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfirmCVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfirmCVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfirmCVResponse proto.InternalMessageInfo

type MsgCreateCompanyWorkedIn struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Uuid           string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CompanyName    string `protobuf:"bytes,3,opt,name=companyName,proto3" json:"companyName,omitempty"`
	TimestampStart string `protobuf:"bytes,4,opt,name=timestampStart,proto3" json:"timestampStart,omitempty"`
	TimestampEnd   string `protobuf:"bytes,5,opt,name=timestampEnd,proto3" json:"timestampEnd,omitempty"`
	Comments       string `protobuf:"bytes,6,opt,name=comments,proto3" json:"comments,omitempty"`
}

func (m *MsgCreateCompanyWorkedIn) Reset()         { *m = MsgCreateCompanyWorkedIn{} }
func (m *MsgCreateCompanyWorkedIn) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCompanyWorkedIn) ProtoMessage()    {}
func (*MsgCreateCompanyWorkedIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5056c0d43a94ec1, []int{6}
}
func (m *MsgCreateCompanyWorkedIn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCompanyWorkedIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCompanyWorkedIn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCompanyWorkedIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCompanyWorkedIn.Merge(m, src)
}
func (m *MsgCreateCompanyWorkedIn) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCompanyWorkedIn) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCompanyWorkedIn.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCompanyWorkedIn proto.InternalMessageInfo

func (m *MsgCreateCompanyWorkedIn) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateCompanyWorkedIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MsgCreateCompanyWorkedIn) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *MsgCreateCompanyWorkedIn) GetTimestampStart() string {
	if m != nil {
		return m.TimestampStart
	}
	return ""
}

func (m *MsgCreateCompanyWorkedIn) GetTimestampEnd() string {
	if m != nil {
		return m.TimestampEnd
	}
	return ""
}

func (m *MsgCreateCompanyWorkedIn) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

type MsgCreateCompanyWorkedInResponse struct {
}

func (m *MsgCreateCompanyWorkedInResponse) Reset()         { *m = MsgCreateCompanyWorkedInResponse{} }
func (m *MsgCreateCompanyWorkedInResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCompanyWorkedInResponse) ProtoMessage()    {}
func (*MsgCreateCompanyWorkedInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5056c0d43a94ec1, []int{7}
}
func (m *MsgCreateCompanyWorkedInResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCompanyWorkedInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCompanyWorkedInResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCompanyWorkedInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCompanyWorkedInResponse.Merge(m, src)
}
func (m *MsgCreateCompanyWorkedInResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCompanyWorkedInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCompanyWorkedInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCompanyWorkedInResponse proto.InternalMessageInfo

type MsgUpdateCompanyWorkedIn struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Uuid           string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CompanyName    string `protobuf:"bytes,3,opt,name=companyName,proto3" json:"companyName,omitempty"`
	TimestampStart string `protobuf:"bytes,4,opt,name=timestampStart,proto3" json:"timestampStart,omitempty"`
	TimestampEnd   string `protobuf:"bytes,5,opt,name=timestampEnd,proto3" json:"timestampEnd,omitempty"`
	Comments       string `protobuf:"bytes,6,opt,name=comments,proto3" json:"comments,omitempty"`
}

func (m *MsgUpdateCompanyWorkedIn) Reset()         { *m = MsgUpdateCompanyWorkedIn{} }
func (m *MsgUpdateCompanyWorkedIn) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCompanyWorkedIn) ProtoMessage()    {}
func (*MsgUpdateCompanyWorkedIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5056c0d43a94ec1, []int{8}
}
func (m *MsgUpdateCompanyWorkedIn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCompanyWorkedIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCompanyWorkedIn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCompanyWorkedIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCompanyWorkedIn.Merge(m, src)
}
func (m *MsgUpdateCompanyWorkedIn) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCompanyWorkedIn) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCompanyWorkedIn.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCompanyWorkedIn proto.InternalMessageInfo

func (m *MsgUpdateCompanyWorkedIn) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateCompanyWorkedIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MsgUpdateCompanyWorkedIn) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *MsgUpdateCompanyWorkedIn) GetTimestampStart() string {
	if m != nil {
		return m.TimestampStart
	}
	return ""
}

func (m *MsgUpdateCompanyWorkedIn) GetTimestampEnd() string {
	if m != nil {
		return m.TimestampEnd
	}
	return ""
}

func (m *MsgUpdateCompanyWorkedIn) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

type MsgUpdateCompanyWorkedInResponse struct {
}

func (m *MsgUpdateCompanyWorkedInResponse) Reset()         { *m = MsgUpdateCompanyWorkedInResponse{} }
func (m *MsgUpdateCompanyWorkedInResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCompanyWorkedInResponse) ProtoMessage()    {}
func (*MsgUpdateCompanyWorkedInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5056c0d43a94ec1, []int{9}
}
func (m *MsgUpdateCompanyWorkedInResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCompanyWorkedInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCompanyWorkedInResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCompanyWorkedInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCompanyWorkedInResponse.Merge(m, src)
}
func (m *MsgUpdateCompanyWorkedInResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCompanyWorkedInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCompanyWorkedInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCompanyWorkedInResponse proto.InternalMessageInfo

type MsgDeleteCompanyWorkedIn struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Uuid    string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (m *MsgDeleteCompanyWorkedIn) Reset()         { *m = MsgDeleteCompanyWorkedIn{} }
func (m *MsgDeleteCompanyWorkedIn) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteCompanyWorkedIn) ProtoMessage()    {}
func (*MsgDeleteCompanyWorkedIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5056c0d43a94ec1, []int{10}
}
func (m *MsgDeleteCompanyWorkedIn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteCompanyWorkedIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteCompanyWorkedIn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteCompanyWorkedIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteCompanyWorkedIn.Merge(m, src)
}
func (m *MsgDeleteCompanyWorkedIn) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteCompanyWorkedIn) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteCompanyWorkedIn.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteCompanyWorkedIn proto.InternalMessageInfo

func (m *MsgDeleteCompanyWorkedIn) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteCompanyWorkedIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type MsgDeleteCompanyWorkedInResponse struct {
}

func (m *MsgDeleteCompanyWorkedInResponse) Reset()         { *m = MsgDeleteCompanyWorkedInResponse{} }
func (m *MsgDeleteCompanyWorkedInResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteCompanyWorkedInResponse) ProtoMessage()    {}
func (*MsgDeleteCompanyWorkedInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5056c0d43a94ec1, []int{11}
}
func (m *MsgDeleteCompanyWorkedInResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteCompanyWorkedInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteCompanyWorkedInResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteCompanyWorkedInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteCompanyWorkedInResponse.Merge(m, src)
}
func (m *MsgDeleteCompanyWorkedInResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteCompanyWorkedInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteCompanyWorkedInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteCompanyWorkedInResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateCV)(nil), "alexs778.cvproject.cvproject.MsgCreateCV")
	proto.RegisterType((*MsgCreateCVResponse)(nil), "alexs778.cvproject.cvproject.MsgCreateCVResponse")
	proto.RegisterType((*MsgUpdateCV)(nil), "alexs778.cvproject.cvproject.MsgUpdateCV")
	proto.RegisterType((*MsgUpdateCVResponse)(nil), "alexs778.cvproject.cvproject.MsgUpdateCVResponse")
	proto.RegisterType((*MsgConfirmCV)(nil), "alexs778.cvproject.cvproject.MsgConfirmCV")
	proto.RegisterType((*MsgConfirmCVResponse)(nil), "alexs778.cvproject.cvproject.MsgConfirmCVResponse")
	proto.RegisterType((*MsgCreateCompanyWorkedIn)(nil), "alexs778.cvproject.cvproject.MsgCreateCompanyWorkedIn")
	proto.RegisterType((*MsgCreateCompanyWorkedInResponse)(nil), "alexs778.cvproject.cvproject.MsgCreateCompanyWorkedInResponse")
	proto.RegisterType((*MsgUpdateCompanyWorkedIn)(nil), "alexs778.cvproject.cvproject.MsgUpdateCompanyWorkedIn")
	proto.RegisterType((*MsgUpdateCompanyWorkedInResponse)(nil), "alexs778.cvproject.cvproject.MsgUpdateCompanyWorkedInResponse")
	proto.RegisterType((*MsgDeleteCompanyWorkedIn)(nil), "alexs778.cvproject.cvproject.MsgDeleteCompanyWorkedIn")
	proto.RegisterType((*MsgDeleteCompanyWorkedInResponse)(nil), "alexs778.cvproject.cvproject.MsgDeleteCompanyWorkedInResponse")
}

func init() { proto.RegisterFile("cvproject/tx.proto", fileDescriptor_e5056c0d43a94ec1) }

var fileDescriptor_e5056c0d43a94ec1 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xc9, 0xf7, 0xb4, 0x70, 0x58, 0x68, 0x65, 0x59, 0x95, 0x15, 0x2c, 0x84, 0x0a, 0x87,
	0x44, 0x14, 0xa9, 0xe9, 0x09, 0xa9, 0xa4, 0x48, 0xe4, 0x50, 0x84, 0x52, 0xa5, 0x48, 0x5c, 0x8a,
	0x6b, 0x0f, 0xa9, 0x49, 0xd6, 0x6b, 0x79, 0x37, 0x25, 0xf9, 0x15, 0xf0, 0xb3, 0x38, 0x16, 0x4e,
	0x1c, 0x51, 0xf2, 0x1b, 0xb8, 0x71, 0x40, 0xfe, 0x8c, 0x13, 0x1c, 0xc7, 0x85, 0x1b, 0xb7, 0xdd,
	0xb7, 0x3b, 0xfb, 0xe6, 0xbd, 0x99, 0x5d, 0x2d, 0x10, 0xe3, 0xca, 0x71, 0xd9, 0x07, 0x34, 0x44,
	0x53, 0x8c, 0x1b, 0x8e, 0xcb, 0x04, 0x23, 0xbb, 0xfa, 0x10, 0xc7, 0xbc, 0xd5, 0x3a, 0x6c, 0xc4,
	0x8b, 0xf3, 0x91, 0x92, 0x88, 0x30, 0xae, 0x82, 0x08, 0xe5, 0x7e, 0x02, 0x63, 0xd4, 0xd1, 0xed,
	0xc9, 0xf9, 0x47, 0xe6, 0x0e, 0xd0, 0x3c, 0xb7, 0xec, 0x60, 0x8b, 0xf6, 0x55, 0x82, 0xcd, 0x13,
	0xde, 0x6f, 0xbb, 0xa8, 0x0b, 0x6c, 0x9f, 0x11, 0x19, 0x2a, 0x86, 0x37, 0x66, 0xae, 0x2c, 0xd5,
	0xa5, 0xbd, 0x5a, 0x37, 0x9a, 0x12, 0x02, 0x45, 0x5b, 0xa7, 0x28, 0xdf, 0xf2, 0x61, 0x7f, 0x4c,
	0x76, 0xa1, 0x86, 0xe6, 0xc8, 0xd0, 0x85, 0xc5, 0x6c, 0xb9, 0xe0, 0x2f, 0xcc, 0x01, 0xef, 0x2c,
	0x3e, 0xa2, 0x54, 0x77, 0x27, 0x72, 0x31, 0x38, 0x2b, 0x9c, 0x92, 0x1d, 0x28, 0xf3, 0x81, 0x35,
	0x1c, 0x72, 0xb9, 0xe4, 0x2f, 0x84, 0x33, 0xa2, 0x02, 0xe0, 0xd8, 0x41, 0xd7, 0x42, 0xdb, 0x40,
	0xb9, 0xec, 0xaf, 0x25, 0x10, 0xf2, 0x00, 0x6e, 0x07, 0x42, 0x2c, 0xe4, 0xbd, 0x5e, 0xe7, 0x58,
	0xae, 0xd4, 0x0b, 0x7b, 0xb5, 0xee, 0x22, 0xa8, 0x6d, 0xc3, 0xdd, 0x84, 0xa4, 0x2e, 0x72, 0x87,
	0xd9, 0x1c, 0xb5, 0x9f, 0x81, 0xd4, 0x9e, 0x63, 0xae, 0x93, 0xaa, 0xc1, 0x96, 0xc1, 0x38, 0x65,
	0xfc, 0xc8, 0x74, 0x91, 0xf3, 0x50, 0xf2, 0x02, 0x16, 0xdb, 0x51, 0x58, 0x65, 0x47, 0x31, 0xc3,
	0x8e, 0xd2, 0x2a, 0x3b, 0xca, 0x19, 0x76, 0x54, 0xd6, 0xdb, 0x51, 0x5d, 0x6d, 0x47, 0x24, 0x3b,
	0xb6, 0xe3, 0x1d, 0x6c, 0x79, 0x2e, 0x31, 0xfb, 0xbd, 0xe5, 0xd2, 0x1b, 0x57, 0x7e, 0xd9, 0xa2,
	0xc2, 0x9f, 0x16, 0x69, 0x3b, 0x70, 0x2f, 0xc9, 0x10, 0x33, 0x7f, 0x93, 0x40, 0x9e, 0x17, 0x28,
	0x68, 0xcc, 0x37, 0x7e, 0x5f, 0x76, 0xec, 0xec, 0x34, 0x46, 0x23, 0xcb, 0x8c, 0xd2, 0xf0, 0xc6,
	0xa4, 0x0e, 0x9b, 0x61, 0x67, 0xbf, 0x9a, 0x17, 0x23, 0x09, 0x91, 0x87, 0x70, 0x47, 0x58, 0x14,
	0xb9, 0xd0, 0xa9, 0x73, 0x2a, 0x74, 0x57, 0x84, 0x85, 0x59, 0x42, 0x3d, 0x41, 0x31, 0xf2, 0xc2,
	0x36, 0xc3, 0x12, 0x2d, 0x60, 0x44, 0x81, 0xaa, 0xc1, 0x28, 0x45, 0x5b, 0x44, 0x95, 0x8a, 0xe7,
	0x9a, 0x06, 0xf5, 0x55, 0x9a, 0x96, 0x85, 0x87, 0xa5, 0xf8, 0xaf, 0x84, 0xa7, 0x6a, 0x8a, 0x85,
	0xbf, 0xf4, 0x75, 0x1f, 0xe3, 0x10, 0xff, 0x51, 0x77, 0xc8, 0x96, 0x7a, 0x52, 0xc4, 0xb6, 0xff,
	0xab, 0x04, 0x85, 0x13, 0xde, 0x27, 0x97, 0x50, 0x8d, 0xdf, 0xb5, 0x47, 0x8d, 0xac, 0xd7, 0xb3,
	0x91, 0x78, 0x2f, 0x94, 0x27, 0xb9, 0xb7, 0x46, 0x8c, 0x1e, 0x53, 0xfc, 0xac, 0xac, 0x67, 0x8a,
	0xb6, 0xe6, 0x60, 0x5a, 0xbe, 0xb5, 0x64, 0x00, 0xb5, 0xf9, 0x95, 0x7d, 0xbc, 0x3e, 0xd3, 0x68,
	0xaf, 0xb2, 0x9f, 0x7f, 0x6f, 0x4c, 0xf6, 0x49, 0x82, 0xed, 0xf4, 0x5b, 0x7a, 0x90, 0xd7, 0xa3,
	0xc5, 0x38, 0xe5, 0xd9, 0xdf, 0xc5, 0x2d, 0x64, 0x94, 0x7e, 0x7d, 0x0e, 0xf2, 0x7a, 0x79, 0xe3,
	0x8c, 0x32, 0x5b, 0xdb, 0xcf, 0x28, 0xbd, 0xb1, 0xd7, 0x67, 0x94, 0x1a, 0x97, 0x23, 0xa3, 0xcc,
	0xf6, 0x7f, 0xde, 0xf9, 0x32, 0x55, 0xa5, 0xeb, 0xa9, 0x2a, 0xfd, 0x98, 0xaa, 0xd2, 0xe7, 0x99,
	0xba, 0x71, 0x3d, 0x53, 0x37, 0xbe, 0xcf, 0xd4, 0x8d, 0xb7, 0xcd, 0xbe, 0x25, 0x2e, 0x47, 0x17,
	0x0d, 0x83, 0xd1, 0xe6, 0xd1, 0x10, 0xc7, 0xa7, 0xad, 0xd6, 0x61, 0xb3, 0x7d, 0xf6, 0x3a, 0xfc,
	0x23, 0x8c, 0x9b, 0x89, 0x5f, 0xc7, 0xc4, 0x41, 0x7e, 0x51, 0xf6, 0x3f, 0x09, 0x4f, 0x7f, 0x07,
	0x00, 0x00, 0xff, 0xff, 0xa7, 0x10, 0xcc, 0x4c, 0x8f, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateCV(ctx context.Context, in *MsgCreateCV, opts ...grpc.CallOption) (*MsgCreateCVResponse, error)
	UpdateCV(ctx context.Context, in *MsgUpdateCV, opts ...grpc.CallOption) (*MsgUpdateCVResponse, error)
	ConfirmCV(ctx context.Context, in *MsgConfirmCV, opts ...grpc.CallOption) (*MsgConfirmCVResponse, error)
	CreateCompanyWorkedIn(ctx context.Context, in *MsgCreateCompanyWorkedIn, opts ...grpc.CallOption) (*MsgCreateCompanyWorkedInResponse, error)
	UpdateCompanyWorkedIn(ctx context.Context, in *MsgUpdateCompanyWorkedIn, opts ...grpc.CallOption) (*MsgUpdateCompanyWorkedInResponse, error)
	DeleteCompanyWorkedIn(ctx context.Context, in *MsgDeleteCompanyWorkedIn, opts ...grpc.CallOption) (*MsgDeleteCompanyWorkedInResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateCV(ctx context.Context, in *MsgCreateCV, opts ...grpc.CallOption) (*MsgCreateCVResponse, error) {
	out := new(MsgCreateCVResponse)
	err := c.cc.Invoke(ctx, "/alexs778.cvproject.cvproject.Msg/CreateCV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCV(ctx context.Context, in *MsgUpdateCV, opts ...grpc.CallOption) (*MsgUpdateCVResponse, error) {
	out := new(MsgUpdateCVResponse)
	err := c.cc.Invoke(ctx, "/alexs778.cvproject.cvproject.Msg/UpdateCV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ConfirmCV(ctx context.Context, in *MsgConfirmCV, opts ...grpc.CallOption) (*MsgConfirmCVResponse, error) {
	out := new(MsgConfirmCVResponse)
	err := c.cc.Invoke(ctx, "/alexs778.cvproject.cvproject.Msg/ConfirmCV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateCompanyWorkedIn(ctx context.Context, in *MsgCreateCompanyWorkedIn, opts ...grpc.CallOption) (*MsgCreateCompanyWorkedInResponse, error) {
	out := new(MsgCreateCompanyWorkedInResponse)
	err := c.cc.Invoke(ctx, "/alexs778.cvproject.cvproject.Msg/CreateCompanyWorkedIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCompanyWorkedIn(ctx context.Context, in *MsgUpdateCompanyWorkedIn, opts ...grpc.CallOption) (*MsgUpdateCompanyWorkedInResponse, error) {
	out := new(MsgUpdateCompanyWorkedInResponse)
	err := c.cc.Invoke(ctx, "/alexs778.cvproject.cvproject.Msg/UpdateCompanyWorkedIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteCompanyWorkedIn(ctx context.Context, in *MsgDeleteCompanyWorkedIn, opts ...grpc.CallOption) (*MsgDeleteCompanyWorkedInResponse, error) {
	out := new(MsgDeleteCompanyWorkedInResponse)
	err := c.cc.Invoke(ctx, "/alexs778.cvproject.cvproject.Msg/DeleteCompanyWorkedIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateCV(context.Context, *MsgCreateCV) (*MsgCreateCVResponse, error)
	UpdateCV(context.Context, *MsgUpdateCV) (*MsgUpdateCVResponse, error)
	ConfirmCV(context.Context, *MsgConfirmCV) (*MsgConfirmCVResponse, error)
	CreateCompanyWorkedIn(context.Context, *MsgCreateCompanyWorkedIn) (*MsgCreateCompanyWorkedInResponse, error)
	UpdateCompanyWorkedIn(context.Context, *MsgUpdateCompanyWorkedIn) (*MsgUpdateCompanyWorkedInResponse, error)
	DeleteCompanyWorkedIn(context.Context, *MsgDeleteCompanyWorkedIn) (*MsgDeleteCompanyWorkedInResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateCV(ctx context.Context, req *MsgCreateCV) (*MsgCreateCVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCV not implemented")
}
func (*UnimplementedMsgServer) UpdateCV(ctx context.Context, req *MsgUpdateCV) (*MsgUpdateCVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCV not implemented")
}
func (*UnimplementedMsgServer) ConfirmCV(ctx context.Context, req *MsgConfirmCV) (*MsgConfirmCVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmCV not implemented")
}
func (*UnimplementedMsgServer) CreateCompanyWorkedIn(ctx context.Context, req *MsgCreateCompanyWorkedIn) (*MsgCreateCompanyWorkedInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompanyWorkedIn not implemented")
}
func (*UnimplementedMsgServer) UpdateCompanyWorkedIn(ctx context.Context, req *MsgUpdateCompanyWorkedIn) (*MsgUpdateCompanyWorkedInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompanyWorkedIn not implemented")
}
func (*UnimplementedMsgServer) DeleteCompanyWorkedIn(ctx context.Context, req *MsgDeleteCompanyWorkedIn) (*MsgDeleteCompanyWorkedInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCompanyWorkedIn not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateCV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCV)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alexs778.cvproject.cvproject.Msg/CreateCV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCV(ctx, req.(*MsgCreateCV))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCV)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alexs778.cvproject.cvproject.Msg/UpdateCV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCV(ctx, req.(*MsgUpdateCV))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ConfirmCV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConfirmCV)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConfirmCV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alexs778.cvproject.cvproject.Msg/ConfirmCV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConfirmCV(ctx, req.(*MsgConfirmCV))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateCompanyWorkedIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCompanyWorkedIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCompanyWorkedIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alexs778.cvproject.cvproject.Msg/CreateCompanyWorkedIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCompanyWorkedIn(ctx, req.(*MsgCreateCompanyWorkedIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCompanyWorkedIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCompanyWorkedIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCompanyWorkedIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alexs778.cvproject.cvproject.Msg/UpdateCompanyWorkedIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCompanyWorkedIn(ctx, req.(*MsgUpdateCompanyWorkedIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteCompanyWorkedIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteCompanyWorkedIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteCompanyWorkedIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alexs778.cvproject.cvproject.Msg/DeleteCompanyWorkedIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteCompanyWorkedIn(ctx, req.(*MsgDeleteCompanyWorkedIn))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "alexs778.cvproject.cvproject.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCV",
			Handler:    _Msg_CreateCV_Handler,
		},
		{
			MethodName: "UpdateCV",
			Handler:    _Msg_UpdateCV_Handler,
		},
		{
			MethodName: "ConfirmCV",
			Handler:    _Msg_ConfirmCV_Handler,
		},
		{
			MethodName: "CreateCompanyWorkedIn",
			Handler:    _Msg_CreateCompanyWorkedIn_Handler,
		},
		{
			MethodName: "UpdateCompanyWorkedIn",
			Handler:    _Msg_UpdateCompanyWorkedIn_Handler,
		},
		{
			MethodName: "DeleteCompanyWorkedIn",
			Handler:    _Msg_DeleteCompanyWorkedIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cvproject/tx.proto",
}

func (m *MsgCreateCV) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCV) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCV) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CompaniesUUID) > 0 {
		for iNdEx := len(m.CompaniesUUID) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CompaniesUUID[iNdEx])
			copy(dAtA[i:], m.CompaniesUUID[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.CompaniesUUID[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Experience) > 0 {
		i -= len(m.Experience)
		copy(dAtA[i:], m.Experience)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Experience)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Skills) > 0 {
		i -= len(m.Skills)
		copy(dAtA[i:], m.Skills)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Skills)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Summary) > 0 {
		i -= len(m.Summary)
		copy(dAtA[i:], m.Summary)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Summary)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Education) > 0 {
		i -= len(m.Education)
		copy(dAtA[i:], m.Education)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Education)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCVResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCVResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCVResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCV) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCV) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCV) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CompaniesUUID) > 0 {
		for iNdEx := len(m.CompaniesUUID) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CompaniesUUID[iNdEx])
			copy(dAtA[i:], m.CompaniesUUID[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.CompaniesUUID[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Experience) > 0 {
		i -= len(m.Experience)
		copy(dAtA[i:], m.Experience)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Experience)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Skills) > 0 {
		i -= len(m.Skills)
		copy(dAtA[i:], m.Skills)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Skills)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Summary) > 0 {
		i -= len(m.Summary)
		copy(dAtA[i:], m.Summary)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Summary)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Education) > 0 {
		i -= len(m.Education)
		copy(dAtA[i:], m.Education)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Education)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CosmosAdress) > 0 {
		i -= len(m.CosmosAdress)
		copy(dAtA[i:], m.CosmosAdress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CosmosAdress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCVResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCVResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCVResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgConfirmCV) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfirmCV) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfirmCV) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CosmosAdress) > 0 {
		i -= len(m.CosmosAdress)
		copy(dAtA[i:], m.CosmosAdress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CosmosAdress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgConfirmCVResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfirmCVResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfirmCVResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateCompanyWorkedIn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCompanyWorkedIn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCompanyWorkedIn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Comments) > 0 {
		i -= len(m.Comments)
		copy(dAtA[i:], m.Comments)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Comments)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.TimestampEnd) > 0 {
		i -= len(m.TimestampEnd)
		copy(dAtA[i:], m.TimestampEnd)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TimestampEnd)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TimestampStart) > 0 {
		i -= len(m.TimestampStart)
		copy(dAtA[i:], m.TimestampStart)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TimestampStart)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CompanyName) > 0 {
		i -= len(m.CompanyName)
		copy(dAtA[i:], m.CompanyName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CompanyName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCompanyWorkedInResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCompanyWorkedInResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCompanyWorkedInResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCompanyWorkedIn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCompanyWorkedIn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCompanyWorkedIn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Comments) > 0 {
		i -= len(m.Comments)
		copy(dAtA[i:], m.Comments)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Comments)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.TimestampEnd) > 0 {
		i -= len(m.TimestampEnd)
		copy(dAtA[i:], m.TimestampEnd)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TimestampEnd)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TimestampStart) > 0 {
		i -= len(m.TimestampStart)
		copy(dAtA[i:], m.TimestampStart)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TimestampStart)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CompanyName) > 0 {
		i -= len(m.CompanyName)
		copy(dAtA[i:], m.CompanyName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CompanyName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCompanyWorkedInResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCompanyWorkedInResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCompanyWorkedInResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteCompanyWorkedIn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteCompanyWorkedIn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteCompanyWorkedIn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteCompanyWorkedInResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteCompanyWorkedInResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteCompanyWorkedInResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateCV) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Education)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Summary)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Skills)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Experience)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.CompaniesUUID) > 0 {
		for _, s := range m.CompaniesUUID {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgCreateCVResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateCV) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CosmosAdress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Education)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Summary)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Skills)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Experience)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.CompaniesUUID) > 0 {
		for _, s := range m.CompaniesUUID {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateCVResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgConfirmCV) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CosmosAdress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgConfirmCVResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateCompanyWorkedIn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CompanyName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TimestampStart)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TimestampEnd)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Comments)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateCompanyWorkedInResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateCompanyWorkedIn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CompanyName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TimestampStart)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TimestampEnd)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Comments)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateCompanyWorkedInResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteCompanyWorkedIn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteCompanyWorkedInResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateCV) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCV: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCV: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Education", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Education = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Summary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Summary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skills", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Skills = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Experience", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Experience = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompaniesUUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CompaniesUUID = append(m.CompaniesUUID, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCVResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCVResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCVResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCV) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCV: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCV: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosAdress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosAdress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Education", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Education = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Summary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Summary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skills", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Skills = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Experience", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Experience = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompaniesUUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CompaniesUUID = append(m.CompaniesUUID, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCVResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCVResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCVResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfirmCV) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfirmCV: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfirmCV: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosAdress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosAdress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfirmCVResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfirmCVResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfirmCVResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCompanyWorkedIn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCompanyWorkedIn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCompanyWorkedIn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompanyName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CompanyName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampStart", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimestampStart = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampEnd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimestampEnd = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comments", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comments = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCompanyWorkedInResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCompanyWorkedInResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCompanyWorkedInResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCompanyWorkedIn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCompanyWorkedIn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCompanyWorkedIn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompanyName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CompanyName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampStart", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimestampStart = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampEnd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimestampEnd = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comments", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comments = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCompanyWorkedInResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCompanyWorkedInResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCompanyWorkedInResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteCompanyWorkedIn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteCompanyWorkedIn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteCompanyWorkedIn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteCompanyWorkedInResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteCompanyWorkedInResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteCompanyWorkedInResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
